INSERT INTO USER(ID,USERID,PASSWORD,NAME,EMAIL) VALUES (1,'nayha','1111','TEST_IN','TEST@E.net');
INSERT INTO USER(ID,USERID,PASSWORD,NAME,EMAIL) VALUES (2,'nayha2','1111','TEST_2','TES22@2.net');

INSERT INTO QUESTION (ID,WRITER_ID,TITLE,CONTENTS,CREATE_DATE) VALUES(1,1,'제목','내용쓰',CURRENT_TIMESTAMP());
INSERT INTO QUESTION (ID,WRITER_ID,TITLE,CONTENTS,CREATE_DATE) VALUES(2,2,'제목222','내용쓰2222',CURRENT_TIMESTAMP());